
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ANDTRAINING_PROFILE BATCH_SIZE CREATE DELIMITER EPOCH FLOAT FORMULA FORMULA_OPERATOR INTEGER MODEL REGULARIZER SQL SUFFLE TRAIN TRAINING_PROFILE TYPE WITH WORDexpression : CREATE MODEL WORD TYPE WORD REGULARIZER WORD DELIMITERexpression : SQL DELIMITER'
    
_lr_action_items = {'CREATE':([0,],[2,]),'SQL':([0,],[3,]),'$end':([1,5,11,],[0,-2,-1,]),'MODEL':([2,],[4,]),'DELIMITER':([3,10,],[5,11,]),'WORD':([4,7,9,],[6,8,10,]),'TYPE':([6,],[7,]),'REGULARIZER':([8,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> CREATE MODEL WORD TYPE WORD REGULARIZER WORD DELIMITER','expression',8,'p_create_model','parser.py',9),
  ('expression -> SQL DELIMITER','expression',2,'p_SQL','parser.py',16),
]
